export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_ITEM_CART = 'REMOVE_ITEM_CART';
export const EMPTY_CART = 'EMPTY_CART';
export const SAVE_SHIPPING_INFO = 'SAVE_SHIPPING_INFO'; 
export const LOAD_USER_CART = 'LOAD_USER_CART';
export const LOAD_USER_SHIPPING_INFO = 'LOAD_USER_SHIPPING_INFO';
export const TOGGLE_CART_OVERLAY = 'TOGGLE_CART_OVERLAY';